@startuml

package "simulation"{
  enum Deplacement{
    HAUT
    BAS
    GAUCHE
    DROITE
    DIAG_HAUT_GAUCHE
    DIAG_HAUT_DROITE
    DIAG_BAS_GAUCHE
    DIAG_BAS_DROITE
    AUCUN
  }
  enum Comportements{
    ARBREDETERMINISTE
    ARBREDETERMINISTEV2
    ALEATOIRE
    ARBREALEATOIRE
    RESEAUARBREDETERMINISTE
    RESEAUARBREALEATOIRE
  }
  enum CaseEnum{
    MUR
    SOL
    SORTIE
    SPAWN_PRISONNIER
    SPAWN_GARDIEN
    RACCOURCI_GARDIEN
  }


  package "comportement"{
    class ReseauDeNeurones{
        - translator: Translator<NDArray, Integer>
        + ReseauDeNeurones(String, Simulation, Personnage)
    }
    Interface Comportement{
        + prendreDecision(): Deplacement
        + getType(): Comportements
    }
    class Aleatoire{
        - deplacementAleatoire(): Deplacement
    }
    class ArbreDecision{
        + direction(Position, Position): Deplacement
        + oppose(Deplacement): Deplacement
    }
    class ArbreDecisionGardien{
      + ArbreDecisionGardien(Simulation, Personnage)
    }
    class ArbreDecisionGardienAleatoire{
        + ArbreDecisionGardienAleatoire(Simulation, Personnage)
        - choixDeplacementAleatoire(double[][]): int[]
    }
    class ArbreDecisionPrisonnier{
          + ArbreDecisionPrisonnier(Simulation, Personnage)
          + oppose(Deplacement): Deplacement
    }
    class ArbreDecisionPrisonnier2{
          + ArbreDecisionPrisonnier(Simulation, Personnage)
          + fuir(): Deplacement
    }
  }
  class Simulation{
    - observateurs : List<DessinJeu>
    - nbTours : int
    - victoirePrisonnier : boolean
    - victoireGardien : boolean
    + {static} final CARTE : int[][]
    + {static} final VISION_G : HashMap<Position, ArrayList<Position>>
    + {static} final VISION_P : HashMap<Position, ArrayList<Position>>
    + {static} final VISION_CAMERAS : HashMap<Position, ArrayList<Position>>
    + {static} final CHEMIN_G : HashMap<List<Position>, Stack>
    + {static} final CHEMIN_P : HashMap<List<Position>, Stack>
    - historiquePosition : HashMap<Personnage, List<Position>>
    - historiqueBayesien : HashMap<Personnage, List<double[][]>>
    - historiqueDeplacement : HashMap<Personnage, List<Deplacement>>
    - estFini : boolean
    - carteBayesiennes : HashMap<Personnage, double[][]>
    - bayesiens : HashMap<Personnage, Bayesien>
    + Simulation(boolean, Comportements)
    + Simulation(Comportement, Comportement)
    + Simulation(Simulation)
    + positionnerAgentsSpawnAleatoire(): void
    + positionnerAleatoirement(): void
    + deplacerAgents(): void
    + deplacerPersonnage(Personnage, Deplacement): boolean
    + deplacementJoueur(Deplacement): void
    + verifierDeplacement(Personnage, Personnage): boolean
    + miseAJourFinJeu(): void
    + actualisationBayesienne(Personnage, Personnage): void
    + estVisible(Personnage, boolean): boolean
    + murPresent(int, int): boolean
    + getPrisonnier(): Personnage
    + getGardien(): Personnage
    + getJoueur(): Personnage
    + getPosSortie(): Position
    + getNbTours(): int
    + getCarteBayesienne(): HashMap<Personnage, double[][]>
    + getBayesiens(): HashMap<Personnage, Bayesien>
    + getVictoirePrisonnier(): boolean
    + getVictoireGardien(): boolean
    + getHistoriqueDeplacement(): HashMap<Personnage, List<Deplacement>>
    + getHistoriquePosition(): HashMap<Personnage, List<Position>>
    + getHistoriqueBayesien(): HashMap<Personnage, List<double[][]>>
    + getComportementPrisonnier(): Comportement
    + getComportementGardien(): Comportement
    + setComportementPrisonnier(Comportement): void
    + setComportementGardien(Comportement): void
    + setCarteBayesiennes(HashMap<Personnage, double[][]>): void
    + setBayesiens(HashMap<Personnage, Bayesien>): void
    + setGardien(Personnage): void
    + setPrisonnier(Personnage): void
    + setEstFini(boolean): void
    + setHistoriqueBayesien(HashMap<Personnage, List<double[][]>>): void
    + setHistoriqueDeplacement(HashMap<Personnage, List<Deplacement>>): void
    + setHistoriquePosition(HashMap<Personnage, List<Position>>): void
    + setNbTours(int): void
    + setVictoireGardien(boolean): void
    + setVictoirePersonnage(boolean): void
    + toString(): String
  }

  class Case{
    - x: int
    - y: int
    - contenu: int
  }

  package "personnage"{
    class Bayesien{
      - carteBayesienne: double[][]
      - casesValides : List<Case>
      + Bayesien()
      + calculerProbaPresence(double[][], List<Integer[]>): double[][]
      + getCasesVoisineValide(int, int): List<Case>
      + getPlusGrandeProbas(): List<Case>
      + getCarteBayesienne(): double[][]
    }
    class Position{
     - x: int
     - y: int
     + Position(int, int)
     + setX(int): void
     + setY(int): void
     + getX(): int
     + getY(): int
     + deplacer(int, int): void
     + deplacer(Deplacement): void
     + casesAdjacentes(): ArrayList<Position>
    }

    class Personnage{
      + Personnage(int, int)
      + {abstract} deplacer(Position): void
      + getPosition(): Position
      + setPosition(Position): void
      + getVision(): ArrayList<Position>
    }
    class Agent{
      + Agent(int, int)

    }
    class Joueur{
      + Joueur(int, int)
    }
  }
  package "tuto"{
    enum EtatTuto {
        DEBUT_Perso
        DEPLACEMENT
        GARDIEN
        DEPLACEMENT_GARDIEN
        FIN
    }
    class SimulationTutoriel{
        - etatActuel: EtatTuto
        - gardienVue: boolean
        + SimulationTutoriel()
        + deplacementJoueur(Deplacement): void
        + update(KeyEvent): void
        - getDeplacement(KeyEvent): Deplacement
    }

  }
}


ReseauDeNeurones "1" --> "1" Simulation : simulation
ReseauDeNeurones "1" --> "1" Personnage : personnage
ReseauDeNeurones ..|> Comportement
Aleatoire "1" --> "1" Simulation : simulation
Aleatoire "1" --> "1" Personnage : perso
Aleatoire ..|> Comportement
ArbreDecisionPrisonnier --|> ArbreDecision
ArbreDecisionGardien --|> ArbreDecision
ArbreDecisionPrisonnier ..|> Comportement
ArbreDecisionGardien ..|> Comportement
ArbreDecisionPrisonnier "1" --> "1" Simulation: simulation
ArbreDecisionPrisonnier "1" --> "1" Personnage: personnage
ArbreDecisionGardien "1" --> "1" Simulation: simulation
ArbreDecisionGardien "1" --> "1" Personnage: personnage
ArbreDecisionGardienAleatoire "1" --> "1" Simulation: simulation
ArbreDecisionGardienAleatoire "1" --> "1" Personnage: personnage
ArbreDecisionGardienAleatoire ..|> Comportement
ArbreDecisionGardienAleatoire --|> ArbreDecision
ArbreDecisionPrisonnier2 "1" --> "1" Simulation: simulation
ArbreDecisionPrisonnier2 "1" --> "1" Personnage: personnage
ArbreDecisionPrisonnier2 --|> ArbreDecision
ArbreDecisionPrisonnier2 ..|> Comportement



Bayesien "1" --> "*" Case: casesValides
Agent --|> Personnage
Joueur --|> Personnage
Personnage "1" --> "1" Position : position

Simulation "1" --> "1" Personnage: gardien
Simulation "1" --> "1" Personnage: prisonnier
Simulation "1" --> "1" Comportement: comportementGardien
Simulation "1" --> "1" Comportement: comportementPrisonnier

Simulation <|-- SimulationTutoriel


@enduml
